---
- name: copy root ca
  ansible.builtin.copy:
    src: "{{ splunk.ms_cert_path }}/rootCA.pem"
    dest: "{{ cert_temp.path }}/rootCA.pem"

- name: copy cert and private key
  ansible.builtin.copy:
    src: "{{ splunk.ms_cert_path }}/{{ inventory_hostname }}/{{ item }}"
    dest: "{{ cert_temp.path }}/{{ item }}"
  loop:
    - key.pem
    - "{{ inventory_hostname }}.crt"