---
- name: copy self CA
  ansible.builtin.copy:
    src: "{{ splunk.self_ca_path }}/{{ item }}"
    dest: "{{ cert_temp.path }}/{{ item }}"
  loop:
    - "rootCA.pem"
    - "rootCA.key"

- name: generate certificate private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_temp.path }}/key.pem"
    passphrase: "{{ splunk.ssl.password }}"
    cipher: auto
    format: pkcs8
    size: 2048

- name: create certificate csr file
  community.crypto.openssl_csr:
    path: "{{ cert_temp.path }}/{{ inventory_hostname }}.csr"
    privatekey_path: "{{ cert_temp.path }}/key.pem"
    common_name: "{{ inventory_hostname }}"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: Morgan Stanley
    organizational_unit_name: Technology
    email_address: "{{ splunk.ssl.email_address }}"
    extended_key_usage:
      - clientAuth
      - serverAuth
    privatekey_passphrase: "{{ splunk.ssl.password }}"
    subject_alt_name: "DNS:{{ inventory_hostname}}"

- name: generate certificate with own CA certificate
  community.crypto.x509_certificate:
    path: "{{ cert_temp.path }}/{{ inventory_hostname }}.crt"
    csr_path: "{{ cert_temp.path }}/{{ inventory_hostname }}.csr"
    ownca_path: "{{ cert_temp.path }}/rootCA.pem"
    ownca_privatekey_path: "{{ cert_temp.path }}/rootCA.key"
    ownca_not_after: "+365d"
    provider: ownca
