---
- name: Clean up
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ kafka.base }}/{{ kafka.version }}'

- name: Ensure base install location exists
  ansible.builtin.file:
    path: '{{ kafka.base }}/{{ kafka.version }}'
    state: directory

- name: Install binary
  ansible.builtin.unarchive:
    src: '{{ kafka.binary }}'
    dest: '{{ kafka.base }}/{{ kafka.version }}'
    extra_opts:
      - --strip-components=1