---
- name: Clean up
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - '{{ zookeeper.base }}/{{ zookeeper.version }}'
    - '{{ zookeeper.data_dir }}'

- name: Ensure base install location exists
  ansible.builtin.file:
    path: '{{ zookeeper.base }}/{{ zookeeper.version }}'
    state: directory
  
- name: Install binary
  ansible.builtin.unarchive:
    src: '{{ zookeeper.binary }}'
    dest: '{{ zookeeper.base }}/{{ zookeeper.version }}'
    extra_opts:
      - --strip-components=1

- name: Ensure data directory exists
  ansible.builtin.file:
    path: '{{ zookeeper.data_dir }}'
    state: directory

- name: create myid file
  ansible.builtin.lineinfile:
    path: '{{ zookeeper.data_dir }}/myid'
    line: "{{ lookup('ansible.utils.index_of', groups['zookeeper'], 'eq', inventory_hostname) + 1 }}"
    create: yes
