---
- name: ensure splunk home directory exists
  ansible.builtin.file:
    path: '{{ splunk.home }}'
    state: directory

- name: install splunk from tar file
  ansible.builtin.unarchive:
    src: '{{ splunk.binary }}'
    dest: '{{ splunk.home }}'
    extra_opts:
      - --strip-components=1