---
- name: create temp folder
  ansible.builtin.tempfile:
    state: directory
    prefix: siem_zookeeper
  register: cert_temp

- name: copy self CA
  ansible.builtin.copy:
    src: "{{ zookeeper.self_ca_path }}/{{ item }}"
    dest: "{{ cert_temp.path }}/{{ item }}"
  loop:
    - "rootCA.pem"
    - "rootCA.key"

- name: generate certificate private key
  community.crypto.openssl_privatekey:
    path: "{{ cert_temp.path }}/{{ inventory_hostname }}.key"
    passphrase: "{{ zookeeper.keystore_pass }}"
    cipher: auto
    format: pkcs8
    size: 2048

- name: create certificate csr file
  community.crypto.openssl_csr:
    path: "{{ cert_temp.path }}/{{ inventory_hostname }}.csr"
    privatekey_path: "{{ cert_temp.path }}/{{ inventory_hostname }}.key"
    common_name: "{{ inventory_hostname }}"
    country_name: CN
    state_or_province_name: Shanghai
    locality_name: Shanghai
    organization_name: Morgan Stanley
    organizational_unit_name: Technology
    email_address: cod-siem@ms.com
    extended_key_usage:
      - clientAuth
      - serverAuth
    privatekey_passphrase: "{{ zookeeper.keystore_pass }}"
    subject_alt_name: "DNS:{{ inventory_hostname}}"

- name: generate certificate with own CA certificate
  community.crypto.x509_certificate:
    path: "{{ cert_temp.path }}/{{ inventory_hostname }}.crt"
    csr_path: "{{ cert_temp.path }}/{{ inventory_hostname }}.csr"
    ownca_path: "{{ cert_temp.path }}/rootCA.pem"
    ownca_privatekey_path: "{{ cert_temp.path }}/rootCA.key"
    ownca_not_after: "+365d"
    provider: ownca

- name: create security folder
  ansible.builtin.file:
    path: "{{ zookeeper.base }}/{{ zookeeper.version }}/security"
    state: directory

- name: create pkcs12 file
  ansible.builtin.command:
    cmd: >
      openssl pkcs12 -export
      -inkey {{ inventory_hostname }}.key
      -in {{ inventory_hostname }}.crt
      -out keystore.p12      
      -password "pass:{{ zookeeper.keystore_pass }}"
      -passin "pass:{{ zookeeper.keystore_pass }}"
    chdir: "{{ cert_temp.path }}"

- name: create truststore
  ansible.builtin.command:
    cmd: >
      keytool -import -file rootCA.pem
      -keystore truststore.p12
      -storetype pkcs12
      -storepass {{ zookeeper.truststore_pass }} -noprompt
    chdir: "{{ cert_temp.path }}"

- name: create security folder
  ansible.builtin.file:
    path: '{{ zookeeper.base }}/{{ zookeeper.version }}/security'
    state: directory

- name: install keystore and truststore
  ansible.builtin.copy:
    remote_src: yes
    src: '{{ cert_temp.path }}/{{ item }}'
    dest: '{{ zookeeper.base }}/{{ zookeeper.version }}/security/{{ item }}'
  loop:
    - keystore.p12
    - truststore.p12