---

- name: update kafka config
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ kafka.base }}/{{ kafka.version }}/{{ item }}'
  loop:
    - config/client.properties
    - config/server.properties

- name: update kafka script
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ kafka.base }}/{{ kafka.version }}/{{ item }}'
    mode: 0755
  loop:
    - bin/kafka-topics.sh