---
- name: install kafka
  hosts: kafka
  collections:
    - siem.kafka
  tasks:
    - import_role:
        name: kafka-binary-install
  tags:
    - install

- name: install certificate
  gather_facts: yes
  hosts: kafka
  collections:
    - siem.kafka
  tasks:
    - import_role:
        name: kafka-certificate-install
  tags:
    - install_certificate

- name: update config
  hosts: kafka
  collections:
    - siem.kafka
  tasks:
    - import_role:
        name: kafka-config-update
  tags:
    - update_config