---
- name: install zookeeper
  hosts: zookeeper
  collections:
    - siem.zookeeper
  tasks:
    - import_role:
        name: zookeeper-binary-install
  tags:
    - install

- name: update config
  hosts: zookeeper
  collections:
    - siem.zookeeper
  tasks:
    - import_role:
        name: zookeeper-config-update
  tags:
    - update_config

- name: install certificate
  hosts: zookeeper
  collections:
    - siem.zookeeper
  tasks:
    - import_role:
        name: zookeeper-certificate-install
  tags:
    - install_cert
  environment:
    PATH: /home/ubuntu/amazon-corretto-17.0.1.12.1-linux-x64/bin:{{ ansible_env.PATH }}
